loopback_users.guest = false
listeners.tcp.default = 5672
management.tcp.port = 15672

# Enable plugins
management_agent.disable_metrics_collector = false

# Prometheus metrics
prometheus.tcp.port = 15692
prometheus.path = /metrics


# # Cluster & discovery: Recommended for production hardening
# cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
# cluster_formation.classic_config.nodes.1 = rabbit@localhost

# # Memory watermark (prevent OOM kills)
# vm_memory_high_watermark.relative = 0.6
# vm_memory_high_watermark_paging_ratio = 0.75

# # Disk free limit
# disk_free_limit.absolute = 2GB

# # Management & Prometheus
# management.load_definitions = /etc/rabbitmq/definitions.json  # if using definitions
# prometheus.retention = 60