# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: backend-config
# data:
# {{- range $k, $v := .Values.env }}
#   {{ $k }}: "{{ $v }}"
# {{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  mongo-database: shopsphereDB
  port: "5000"
  cors-origin: "*"
  mongo-auth-source: admin
  node-env: production
