apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: luxe-frontend
  source:
    repoURL: https://github.com/YOUR_REPO/luxe-gitops
    targetRevision: HEAD
    path: charts/frontend
    helm:
      valueFiles:
        - ../../environments/kind/frontend-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true