apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: luxe-infra
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP