apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: luxe-infra
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: luxeadmin
  MONGO_INITDB_ROOT_PASSWORD: luxeadmin-strong-root-password