apiVersion: v1
kind: Secret
metadata:
  name: taskflow-db-secrets
type: Opaque
stringData:
  MONGO_USER: "taskflowuser"
  MONGO_PASSWORD: "taskflowpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: taskflow-rabbitmq-secrets
type: Opaque
stringData:
  RABBITMQ_USER: "taskflow"
  RABBITMQ_PASSWORD: "taskflow2024"

---
apiVersion: v1
kind: Secret
metadata:
  name: taskflow-app-credentials
type: Opaque
stringData:
  MONGO_URI: "mongodb://taskflowuser:taskflowpassword@mongodb:27017/taskflow?authSource=admin"
  RABBITMQ_URL_LINK: "amqp://taskflow:taskflow2024@rabbitmq:5672"
  JWT_SECRET: "your-secret-key-change-in-production"



