# Public frontend  nginx configuration
server {
  listen 80;

  # Serve static files (Vite build output)
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }



  # Nginx internal metrics (Prometheus will NOT hit this directly)
  # location /stub_status {
  #   stub_status;
  #   allow 127.0.0.1;
  #   deny all;
  # }

  # location /stub_status {
  #   stub_status;
  #   allow all;
  # }

  # Proxy API requests to backend
  location /api/ {
    proxy_pass http://backend:5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Cookie $http_cookie;  # ← ADD THIS
  }

  # Proxy uploads to backend
  location /uploads/ {
    proxy_pass http://backend:5000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }
}

# Internal metrics-only server for Prometheus scraping
server {
  listen 127.0.0.1:8080;

  location /stub_status {
    stub_status;
    allow 127.0.0.1;
    deny all;
  }
}
