apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: luxe-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3008"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: payment-service
  ports:
  - port: 3008
    targetPort: 3008
  type: ClusterIP