apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: luxe-backend
  labels:
    app: payment-service
    tier: business-logic
spec:
  selector:
    app: payment-service
  ports:
    - name: metrics
      port: 3008
      targetPort: 3008
  type: ClusterIP