# Use the official NGINX image as the base image
FROM nginx:latest

# Copy custom HTML files into the default NGINX location
COPY ./index.html /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

