apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: luxe-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3013"
    prometheus.io/path: "/metrics"
  labels:
      app: analytics-service
      tier: business-logic
spec:
  selector:
    app: analytics-service
  ports:
  - port: 3013
    targetPort: 3013
  type: ClusterIP