apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: luxe-backend
  labels:
    app: recommendation-service
    tier: business-logic
spec:
  selector:
    app: recommendation-service
  ports:
    - name: metrics
      port: 3014
      targetPort: 3014
  type: ClusterIP