apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: luxe-backend
  labels:
    app: product-service
    tier: business-logic
spec:
  selector:
    app: product-service
  ports:
    - name: metrics
      port: 3003
      targetPort: 3003
  type: ClusterIP