apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: luxe-infra
  labels:
    app: mongodb-exporter
    tier: monitoring
spec:
  selector:
    app: mongodb-exporter
  ports:
  - name: metrics
    port: 9216
    targetPort: 9216