# image: mongo:6
namespace: shopsphere

mongo:
  image: mongo:6
  port: 27017
  storage: 5Gi

secrets:
  mongo:
    secretName: mongo-secret
    mappings:
      - secretKey: mongodb-usr
      - secretKey: mongodb-pwd
