apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: luxe-backend
  labels:
    app: inventory-service
    tier: business-logic
spec:
  selector:
    app: inventory-service
  ports:
    - name: metrics
      port: 3011
      targetPort: 3011
  type: ClusterIP