apiVersion: v1
kind: Secret
metadata:
  name: luxecart-auth-secrets
  namespace: luxe-backend
type: Opaque
stringData:
  JWT_SECRET: your-secret-key-change-in-production
  REDIS_URL: redis://:luxe-cart-redis-password@redis.luxe-infra.svc.cluster.local:6379
  RABBITMQ_URL: amqp://ecommerce:strong-rabbit-password@rabbitmq.luxe-infra.svc.cluster.local:5672
  DATABASE_URL: postgresql://ecommerce:ecommerce123@postgres.luxe-infra.svc.cluster.local:5432/ecommerce
  MONGODB_URL: mongodb://luxeadmin:luxeadmin-strong-root-password@mongodb.luxe-infra.svc.cluster.local:27017/maildb?authSource=admin
  ELASTICSEARCH_URL: http://elasticsearch.luxe-infra.svc.cluster.local:9200
  SMTP_USER: noreply@luxecart.com
  FROM_EMAIL: LuxeCart <noreply@luxecart.com>
  SMTP_PASSWORD: my-smtp-password-in-production