postgresql:
  auth:
    username: postgres
    password: postgres
    database: luxe

redis:
  auth:
    enabled: false

rabbitmq:
  auth:
    username: guest
    password: guest

mongodb:
  replicas: 1
  persistence:
      size: 5Gi
      storageClass: "standard"   # kind-safe, override in EKS

elasticsearch:
  replicas: 1
  persistence:
      size: 5Gi
      storageClass: "standard"   # kind-safe, override in EKS



