apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: observability
  # labels:
  #   Release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - shopsphere
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

