apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: luxe-infra
  labels:
    app: elasticsearch
    tier: monitoring
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http