apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: luxe-infra
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9200"
    prometheus.io/path: "/metrics"
  labels:
    app: elasticsearch
    tier: monitoring
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http