apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: luxe-infra
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9114"
    prometheus.io/path: "/metrics"
  labels:
    app: elasticsearch-exporter
    tier: monitoring

spec:
  selector:
    app: elasticsearch-exporter
  ports:
  - name: metrics
    port: 9114
    targetPort: 9114