apiVersion: v1
kind: Secret
metadata:
  name: taskflow-db-secrets
type: Opaque
stringData:
  MONGO_USER: "taskflowuser"
  MONGO_PASSWORD: "taskflowpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: taskflow-app-credentials
type: Opaque
stringData:
  MONGO_URI: "mongodb://taskflowuser:taskflowpassword@mongodb:27017/taskflow?authSource=admin"
  JWT_SECRET: "your-secret-key-change-in-production"

