apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.aws.secretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.aws.credentialsSecret }}
            key: {{ .Values.aws.accessKeyField }}
          secretAccessKeySecretRef:
            name: {{ .Values.aws.credentialsSecret }}
            key: {{ .Values.aws.secretKeyField }}
