apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: observability
  # labels:
  #   Release: monitoring
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - shopsphere
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
