# prometheus-values.yaml
prometheus:

    # Service
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    retention: 7d
    # ServiceMonitor discovery
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    
    # PodMonitor discovery (optional)
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    
    # Storage
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    
    # Resources
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    
    # Scrape interval
    scrapeInterval: 15s
    evaluationInterval: 15s
    


# # Grafana (included in stack)
# grafana:
#   enabled: true
#   adminUser: admin
#   adminPassword: admin
#   service: 
#     type: NodePort
#     nodePort: 30300
  
#   # Persistence
#   persistence:
#     enabled: true
#     storageClassName: standard
#     size: 5Gi
  
#   # Service
#   service:
#     type: ClusterIP
#     port: 3000
  
#   # Datasources (auto-configured)
#   additionalDataSources:
#     - name: Loki
#       type: loki
#       access: proxy
#       url: http://loki-gateway.luxe-observability.svc.cluster.local:80
#       editable: true

# # Alertmanager
# alertmanager:
#   alertmanagerSpec:
#     storage:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: standard
#           accessModes: ["ReadWriteOnce"]
#           resources:
#             requests:
#               storage: 2Gi

# # Node Exporter (for node metrics)
# nodeExporter:
#   enabled: true

# # Kube State Metrics (for k8s object metrics)
# kubeStateMetrics:
#   enabled: true

# # Disable default dashboards to reduce noise
# defaultDashboardsEnabled: false