apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: luxe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: princewillopah2/luxecart-analytics-service:1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 3013
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: luxecart-auth-secrets
              key: DATABASE_URL

        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3013
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 25
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 3013
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 25
          failureThreshold: 15

