apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  TASK_SERVICE_URL: "http://task-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3003"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3004"