apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.backend.secretName }}
spec:
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.backend.secretName }}
  data:
    - secretKey: {{ .Values.backend.jwtKey }}
      remoteRef:
        key: {{ .Values.backend.awsSecretName }}
        property: jwt-secret
    - secretKey: {{ .Values.backend.mongoUriKey }}
      remoteRef:
        key: {{ .Values.backend.awsSecretName }}
        property: mongo-uri
