apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.mongo.secretName }}
spec:
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.mongo.secretName }}
  data:
    - secretKey: {{ .Values.mongo.usernameKey }}
      remoteRef:
        key: {{ .Values.mongo.awsSecretName }}
        property: mongo-root-username
    - secretKey: {{ .Values.mongo.passwordKey }}
      remoteRef:
        key: {{ .Values.mongo.awsSecretName }}
        property: mongo-root-password
