apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: luxe-infra
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      name: http