kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: true
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP

    - containerPort: 443
      hostPort: 443
      protocol: TCP

  - role: worker

# This configuration allows for a single control-plane node and one worker node. 
# The control-plane node has port mappings for HTTP (80) and HTTPS (443) to allow access to services running in the cluster from the host machine. 
# The pod subnet and service subnet are defined to ensure proper networking within the cluster.


# # run :
  #kind create cluster --config cluster-a.yaml

# # Install Calico only
# kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/calico.yaml

# # Wait until pods are running - this will take about 8 minutes
# kubectl get pods -n kube-system | grep calico