apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: luxe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: princewillopah2/luxecart-inventory-service:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3011
        env:
        - name: LOW_STOCK_THRESHOLD
          value: "10"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: luxecart-auth-secrets
              key: DATABASE_URL
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: luxecart-auth-secrets
              key: RABBITMQ_URL
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3011
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 25
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 3011
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 25
          failureThreshold: 15

