apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: luxe-backend
spec:
  selector:
    app: notification-service
  ports:
  - port: 3009
    targetPort: 3009
  type: ClusterIP