apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: luxe-infra
type: Opaque
stringData:
  POSTGRES_USER: ecommerce
  POSTGRES_PASSWORD: ecommerce123
  POSTGRES_DB: ecommerce
  FLYWAY_USER: ecommerce
  FLYWAY_PASSWORD: ecommerce123
  FLYWAY_URL: jdbc:postgresql://postgres.luxe-infra.svc.cluster.local:5432/ecommerce
  POSTGRES_DB_URL: postgresql://ecommerce:ecommerce123@postgres.luxe-infra.svc.cluster.local:5432/ecommerce?sslmode=disable
