apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app-name.backend }}  # backend
  namespace: {{ .Values.monitor-namespace }} # observability
  # labels:
  #   Release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.app-name.backend }}
  namespaceSelector:
    matchNames:
      - {{ .Values.app-namespace }} # taskflow-ns
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

