apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
  namespace: xxx2
  labels:
    app: frontend-nginx
spec:
  selector:
    app: frontend-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
