apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: luxe-infra
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana

  template:
    metadata:
      labels:
        app: kibana

    spec:
      containers:
        - name: kibana
          image: kibana:8.13.4

          ports:
            - containerPort: 5601

          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.luxe-infra.svc.cluster.local:9200

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5