apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: luxe-backend
  labels:
    app: email-service
    tier: business-logic
spec:
  selector:
    app: email-service
  ports:
    - name: metrics
      port: 3015
      targetPort: 3015
  type: ClusterIP