apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: luxe-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3015"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: email-service
  ports:
  - port: 3015
    targetPort: 3015
  type: ClusterIP